# Ansible playbook
#
# To provision:
#    ansible-playbook -i <inventory> playbook.yml
#
# VERSION 0.1
# ANSIBLE-VERSION 1.2.2

- hosts: vagrant
  user: vagrant
  sudo: True

  tasks:
    - user: name=ansible groups=admin shell=/bin/bash password=ansible state=present
    - file: path=/etc/sudoers.d mode=0770 owner=root group=root state=directory
    - copy: src=files/etc/sudoers dest=/etc/sudoers mode=0440 owner=root group=root
    - command: cat /home/vagrant/.ssh/authorized_keys
      register: authorized_keys
    - authorized_key: user=ansible key="{{ item }}"
      with_items: authorized_keys.stdout_lines


- hosts: app
  user: ansible
  sudo: True

  tasks:
    - name: update apt
      apt: update_cache=yes cache_valid_time=3600

    - name: install apt packages
      apt: name="{{ item }}"
      with_items:
        - build-essential
        - python
        - python-dev
        - python-setuptools
        - python-pip
        - python-numpy
        - python-opencv
        - python-pycurl
        - libjpeg-dev
        - libfreetype6-dev
        - zlib1g-dev
        - libwebp-dev
        - liblcms2-dev

    - name: install pip packages
      pip: >
        name={{ item.name }}
        version={{ item.version }}
        use_mirrors=yes
      with_items:
        - { name: 'Pillow', version: '2.6.1' }
        - { name: 'tornado', version: '4.0.2' }
        - { name: 'coverage', version: '3.6' }
        - { name: 'pep8', version: '1.4.6' }
        - { name: 'pyflakes', version: '0.7.3' }
        - { name: 'pyandoc', version: '0.0.1' }
        - { name: 'sphinx-me', version: '0.2.1' }


- hosts: app
  user: ansible
  sudo: True

  tasks:
    - name: copy pilbox init script
      copy: src=files/etc/init.d/pilbox dest=/etc/init.d/pilbox mode=0755
      notify:
        - restart pilbox

    - name: install pilbox init script
      command: update-rc.d pilbox defaults

    - name: running pilbox check
      service: name=pilbox state=running enabled=yes

  handlers:
    - name: restart pilbox
      service: name=pilbox state=restarted
